#!/bin/bash
#SBATCH --job-name=assembly_pipeline
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=64G
#SBATCH -t 56:00:00
#SBATCH --array=0-3 # please set array to be equal to the number of files you want to process

# Load the environment variables
module purge
module load foss/2022a
module load GCC/11.3.0
module load SPAdes/4.0.0
module load BBMap/39.01
module load bwa-mem2/2.2.1
module load OpenMPI/4.1.4
module load SSPACE_Basic
module load Bowtie/1.3.1
module load HMMER/3.3.2
module load cath-tools/0.16.10
module load seqtk/1.3

#1. Assemble var transcripts from polymorphic reads - keeping samples separate
#rna spades, read error correction on, k-mer 71

filenames=(
*_polymorphic_reads_1.fq
)
active_file=${filenames[$SLURM_ARRAY_TASK_ID]}
file_prefix="${active_file%%_polymorphic_reads_1.fq}"

echo "active_file: $active_file"
echo "file_prefix: $file_prefix"

#rnaspades.py -o "$file_prefix"_SPAdes71 -k 71 -1 "$file_prefix"_polymorphic_reads_1.fq -2 "$file_prefix"_polymorphic_reads_2.fq &&\

#2. Run SSPACE on SPAdes contigs
#SSPACE requires a library.txt file containing insert size estimates- these can be estimated using bbmerge

bbmap.sh in1="$file_prefix"_polymorphic_reads_1.fq in2="$file_prefix"_polymorphic_reads_2.fq ihist="$file_prefix"_bbmerge.txt out=bbmerge_out ref=pf3d7_var_transcripts.fasta &&\

#3.Create library file

insert_size_avg=$(head -1 "$file_prefix"_bbmerge.txt)
insert_size_avg=$(echo "$insert_size_avg" _polymorphic_reads_1.fq  cut -d$'\t' -f2)
insert_size=$(echo "$insert_size_avg" _polymorphic_reads_1.fq  cut -d$'.' -f1)
echo "bwa "$file_prefix"_polymorphic_reads_1.fq "$file_prefix"_polymorphic_reads_2.fq "$insert_size" 0.25 RF" > "$file_prefix"_libraries.txt &&\

# awk command below included to ensure the relevant details are present in the libraries.txt and does not throw out an error
awk '{split($5,x,"."); print $1, $2, $3, x[1], $14, $15}' "$file_prefix"_libraries.txt > tmp && mv tmp "$file_prefix"_libraries.txt &&\

#4.Run SSPACE

perl ~/bin/SSPACE_Basic_v2.0.pl -l "$file_prefix"_libraries.txt -s "$file_prefix"_SPAdes71/transcripts.fasta -n 31 -x 0 -k 10 -b "$file_prefix"_SPAdes71_SSPACE &&\

mv "$file_prefix"_bbmerge.txt bbmerge_libs/"$file_prefix"_bbmerge.txt
mv "$file_prefix"_libraries.txt bbmerge_libs/"$file_prefix"_libraries.txt
mv "$file_prefix"_SPAdes71 SPAdes_intermediates/"$file_prefix"_SPAdes71
mv "$file_prefix"_SPAdes71_SSPACE.final.evidence SPAdes_intermediates/"$file_prefix"_SPAdes71_SSPACE.final.evidence
mv "$file_prefix"_SPAdes71_SSPACE.logfile.txt SPAdes_intermediates/"$file_prefix"_SPAdes71_SSPACE.logfile.txt
mv "$file_prefix"_SPAdes71_SSPACE.summaryfile.txt SPAdes_intermediates/"$file_prefix"_SPAdes71_SSPACE.summaryfile.txt

#5.Annotate the assembled transcripts

hmmsearch --domtblout "$file_prefix"_assembled_transcripts_hmm -E 1e-5 var_domain_hmm "$file_prefix"_SPAdes71_SSPACE.final.scaffolds.fasta &&\

#6.Resolve hits

cath-resolve-hits --input-format hmmer_domtblout "$file_prefix"_assembled_transcripts_hmm --hits-text-to-file "$file_prefix"_assembled_transcripts_hmm_cathresolvehits &&\

mkdir SSPACE_scaffolds
mkdir hmm_assembled_transcripts

mv "$file_prefix"_SPAdes71_SSPACE.final.scaffolds.fasta SSPACE_scaffolds/"$file_prefix"_SPAdes71_SSPACE.final.scaffolds.fasta
mv "$file_prefix"_assembled_transcripts_hmm hmm_assembled_transcripts/"$file_prefix"_assembled_transcripts_hmm


##DO NOT ADD/EDIT BEYOND THIS LINE##
##Job monitor command to list the resource usage
my-job-stats -a -n -s
