#!/bin/bash
#SBATCH --job-name=map_pipeline            
#SBATCH --nodes=1                            
#SBATCH --ntasks=1                           
#SBATCH --cpus-per-task=4                 
#SBATCH --mem=128G                          
#SBATCH -t 12:00:00                          
#SBATCH --array=0-*                          

# please set array to be equal to the number of files you want to process

# -------- Load Required Software Modules --------
module purge                                 
module load GCC/11.3.0
module load OpenMPI/4.1.4
module load R-bundle-Bioconductor/3.16-R-4.2.2
module load Subread/2.0.4                    
module load BCFtools/1.15.1
module load Pysam/0.16.0.1-Python-2.7.18
module load SAMtools/1.16.1                  
module load tabix/0.2.6
module load seqtk/1.3                         
module load parallel

# -------- File Setup --------
filenames=( *_1.fq.gz )                        # Create an array of all input reads
active_file=${filenames[$SLURM_ARRAY_TASK_ID]} # Select file based on job array index
file_prefix="${active_file%%_1.fq.gz}"         # Strip the suffix to get sample prefix

echo "Running pipeline for: $file_prefix"      # Print the current sample being processed

# === 1. HUMAN MAPPING ===
# Align to the human genome to remove host reads
subread-align -t 0 -i human_genome_index -r "${file_prefix}_1.fq.gz" -R "${file_prefix}_2.fq.gz" -o "${file_prefix}_human_mapped.sam" --SAMoutput

# Extract read IDs that did not align to human (flag 4)
samtools view -f 4 "${file_prefix}_human_mapped.sam" | cut -f1 > "${file_prefix}_unmapped_reads.txt"
sort -u "${file_prefix}_unmapped_reads.txt" > "${file_prefix}_unmapped_reads_noDup.txt"

# Extract unmapped reads from original FASTQ files using seqtk
seqtk subseq "${file_prefix}_1.fq.gz" "${file_prefix}_unmapped_reads_noDup.txt" > "${file_prefix}_human_unmapped_1.fq"
seqtk subseq "${file_prefix}_2.fq.gz" "${file_prefix}_unmapped_reads_noDup.txt" > "${file_prefix}_human_unmapped_2.fq" &&\

rm "${file_prefix}_human_mapped.sam" "${file_prefix}_human_mapped.sam.indel.vcf" "${file_prefix}_unmapped_reads.txt"

# === 2. PF MAPPING ===
# Align human-unmapped reads to the P. falciparum transcriptome (excluding var genes)
subread-align -t 0 -i plasmodium_transcripts_novar_index -r "${file_prefix}_human_unmapped_1.fq" -R "${file_prefix}_human_unmapped_2.fq" -o "${file_prefix}_mapped_pf_novar.sam" --SAMoutput

# Extract read IDs not mapping to Pf
samtools view -f 4 "${file_prefix}_mapped_pf_novar.sam" | cut -f1 > "${file_prefix}_Pf_unmapped_reads.txt"
sort -u "${file_prefix}_Pf_unmapped_reads.txt" > "${file_prefix}_Pf_unmapped_reads_noDup.txt"

# Convert SAM to sorted BAM and clean up
samtools view -Sb "${file_prefix}_mapped_pf_novar.sam" | samtools sort -o "${file_prefix}_mapped_pf_novar.bam" &&\

rm "${file_prefix}_mapped_pf_novar.sam" "${file_prefix}_mapped_pf_novar.sam.indel.vcf"

# === 3. RALSTONIA MAPPING ===
# Align same human-unmapped reads to Ralstonia genome (possible contaminant)
subread-align -t 0 -i ralstonia_index -r "${file_prefix}_human_unmapped_1.fq" -R "${file_prefix}_human_unmapped_2.fq" -o "${file_prefix}_ralstonia_mapped.sam" --SAMoutput

# Extract reads not mapping to Ralstonia
samtools view -f 4 "${file_prefix}_ralstonia_mapped.sam" | cut -f1 > "${file_prefix}_ralstonia_unmapped_reads.txt"
sort -u "${file_prefix}_ralstonia_unmapped_reads.txt" > "${file_prefix}_ralstonia_unmapped_reads_noDup.txt" &&\

rm "${file_prefix}_ralstonia_mapped.sam" "${file_prefix}_ralstonia_mapped.sam.indel.vcf" "${file_prefix}_ralstonia_unmapped_reads.txt"

# === 4. POLYMORPHIC READS ===
# Combine Pf-unmapped and Ralstonia-unmapped reads
cat "${file_prefix}_Pf_unmapped_reads_noDup.txt" "${file_prefix}_ralstonia_unmapped_reads_noDup.txt" | sort -u > "${file_prefix}_polymorphic_reads_ids_noDuplicates.txt"

# Extract corresponding polymorphic reads from original FASTQs
seqtk subseq "${file_prefix}_1.fq.gz" "${file_prefix}_polymorphic_reads_ids_noDuplicates.txt" > "${file_prefix}_polymorphic_reads_1.fq"
seqtk subseq "${file_prefix}_2.fq.gz" "${file_prefix}_polymorphic_reads_ids_noDuplicates.txt" > "${file_prefix}_polymorphic_reads_2.fq" &&\

rm "${file_prefix}_Pf_unmapped_reads.txt"

# === 5. ORGANIZE OUTPUT FILES ===
# Move files to appropriate directories
mv "${file_prefix}_1.fq.gz" trim_cat_fq/
mv "${file_prefix}_2.fq.gz" trim_cat_fq/
mv "${file_prefix}_Pf_unmapped_reads_noDup.txt" mapped_txt/Pf_unmapped_reads_txt/
mv "${file_prefix}_unmapped_reads_noDup.txt" mapped_txt/unmapped_reads_noDup_txt/
mv "${file_prefix}_ralstonia_unmapped_reads_noDup.txt" mapped_txt/ralstonia_unmapped_ids_noDup_txt/
mv "${file_prefix}_polymorphic_reads_ids_noDuplicates.txt" mapped_txt/polymorphic_reads/
mv "${file_prefix}_mapped_pf_novar.bam" mapped_txt/mapped_pf_novar_bam/
mv "${file_prefix}_human_unmapped_1.fq" mapped_txt/human_unmapped_fq/
mv "${file_prefix}_human_unmapped_2.fq" mapped_txt/human_unmapped_fq/

# === DO NOT MODIFY BELOW THIS LINE ===
# Track job performance and resource usage
my-job-stats -a -n -s
