#!/bin/bash
#SBATCH --job-name=sig_var_transcripts_filter
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=64G
#SBATCH -t 12:00:00
#SBATCH --array=0-933

# Load the environment variables
module load seqtk/1.3
module load Python/3.11.3
module load BBMap/39.01
module load GCC/11.3.0
module load OpenMPI/4.1.4
module load R/4.4.0
module load BEDTools/2.30.0
module load SAMtools/1.21

# Ensure pandas is available
python -c "import pandas as pd; print(pd.__version__)"

# Get the base sample name
filenames=(
CH1560 #just the sample id
)
active_file=${filenames[$SLURM_ARRAY_TASK_ID]}
file_prefix="${active_file}"

echo "Sample: $file_prefix"

# 1. Run Python script to process HMM annotations
python process_hmm_annotations.py "${file_prefix}_assembled_transcripts_hmm_cathresolvehits" "$file_prefix"

# 2. Extract sig variant transcripts and compute N50
seqtk subseq "${file_prefix}_SPAdes71_SSPACE.final.scaffolds.fasta" "${file_prefix}_assembled_id_sig_annotation.txt" > "${file_prefix}_sig_var_transcripts.fasta"

stats.sh in="${file_prefix}_sig_var_transcripts.fasta" > "${file_prefix}_N50.txt"

# 3. Generate _assembled_id_sig_domains
grep -F -f "${file_prefix}_assembled_id_sig_annotation.txt" "${file_prefix}_assembled_transcripts_hmm_cathresolvehits" | \
awk -F'[[:blank:]]' -v OFS="\t" '{$1=$1; print}' | \
awk '{gsub(/_clustalo_align_v2_v3/,"\t")}1' | \
awk 'BEGIN{FS=OFS="\t"}{print $1,$2,$1,$3,$4,$5,$6,$7,$8}' | \
awk 'BEGIN{FS=OFS="\t"}{gsub(/\|/, "\t", $1)} 1' | \
awk -v var="$file_prefix" 'BEGIN{FS=OFS="\t"}{print var"_"$1"_"$3,$4,$6,$7,$8,$9,$10}' | \
awk -v var="$file_prefix" 'BEGIN{FS=OFS="\t"}{gsub(/\-/, "\t", $5)} 1' > "${file_prefix}_assembled_id_sig_domains"

# 4. Run R script to find unique domains
./unique_domains.r "${file_prefix}"

# 5. Run extract_fasta.r to generate BED
Rscript extract_fasta_updated_2.r

mkdir bed_files/
mkdir extracted_fasta/
# 6. Index FASTA and extract with bedtools
samtools faidx "${file_prefix}_SPAdes71_SSPACE.final.scaffolds.fasta"

bedtools getfasta -fi "${file_prefix}_SPAdes71_SSPACE.final.scaffolds.fasta" -bed "bed_files/${file_prefix}.bed" -name -fo "extracted_fasta/${file_prefix}.extracted.fasta"

##DO NOT ADD/EDIT BEYOND THIS LINE##
##Job monitor command to list the resource usage
my-job-stats -a -n -s
